### ISSUE TITLE
Problème avec PHP 

### ISSUE THREAD

**Issue by Antoineview** [ComFoxx/ManuelNumeriquePDF#1]
`Téléchargement de la page Chapter_001/Page_00001.xhtml...
Convertion et téléchargement de la page sous `./manuel/Chapter_001%2FPage_00001.xhtml.pdf`...
PHP Fatal error:  Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\HttplugFactory, Http\Message\MessageFactory\GuzzleMessageFactory, Http\Message\MessageFactory\DiactorosMessageFactory, Http\Message\MessageFactory\SlimMessageFactory.
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: .

 in /Users/antoine/Downloads/ManuelNumeriquePDF-master/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /Users/antoine/Downloads/ManuelNumeriquePDF-master/vendor/php-http/discovery/src/ClassDiscovery.php(94): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /Users/antoine/Downloads/ManuelNumeriquePDF-master/ven in /Users/antoine/Downloads/ManuelNumeriquePDF-master/vendor/php-http/discovery/src/MessageFactoryDiscovery.php on line 29

Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\HttplugFactory, Http\Message\MessageFactory\GuzzleMessageFactory, Http\Message\MessageFactory\DiactorosMessageFactory, Http\Message\MessageFactory\SlimMessageFactory.
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: .

 in /Users/antoine/Downloads/ManuelNumeriquePDF-master/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /Users/antoine/Downloads/ManuelNumeriquePDF-master/vendor/php-http/discovery/src/ClassDiscovery.php(94): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /Users/antoine/Downloads/ManuelNumeriquePDF-master/ven in /Users/antoine/Downloads/ManuelNumeriquePDF-master/vendor/php-http/discovery/src/MessageFactoryDiscovery.php on line 29
`

**Comment by Deepou1** [comment]
Bonjour,
Est-ce que quelqu'un pourrait m'expliquer comment faire fonctionner le code ?
J'ai bien installé tout ce qui est recommandé, php, composer et docker. J'ai bien vérifié que tout était bien installé.
Cependant je suis complètement bloqué.
Merci d'avance.

**Comment by ComFoxx** [comment]
Malheureusement, ce projet n'est pas maintenu et je ne vais pas pouvoir vous aider beaucoup étant donné que je ne me rappelle même plus comment il fonctionne.
Si votre but est de créer un PDF d'un document Calméo, je vous invite à utiliser https://github.com/ComFoxx/calameo-download-pdf
Autrement, les scripts ne font qu'immiter les horribles lecteurs de manuel des différentes éditions en chargeant pour chaque page le HTML, CSS, les polices d'écriture et les images avant de les envoyer à Gotenberg pour en faire un PDF puis fusionner tous ces PDF en un seul.
Il doit y avoir bien plus simple, mais ça fait des années que j'ai quitté le lycée maintenant, je n'y ai plus d'intérêts alors je ne peux que vous souhaiter bon courrage.
